language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - make composer

script:
    - make standards
    - make test
